on:
  pull_request:
  push:
    branches:
      - main
      - beta
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix flake check --show-trace
  gomod2nix:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    outputs:
      git-head: ${{ steps.commit.outputs.commit_hash || github.sha }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix run .#gomod2nix
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        id: commit
        with:
          commit_message: "chore(deps): update gomod2nix"
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mirkolenz' && github.event_name == 'push' }}
    needs: [check, gomod2nix]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ needs.gomod2nix.outputs.git-head }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
        with:
          platforms: arm64
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
            extra-platforms = aarch64-linux
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix profile install .#release-env
      - run: gomod2nix
      - uses: cihelper/action-semanticrelease-goreleaser@2a2d63554704382e9139a2fb243a9a40ed458e25 # v1
        id: semanticrelease
      - run: nix run .#docker-manifest --impure
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
        env:
          VERSION: ${{ steps.semanticrelease.outputs.version }}
          GH_TOKEN: ${{ github.token }}
