on:
  pull_request:
  push:
jobs:
  gomod2nix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: DeterminateSystems/nix-installer-action@v7
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: |
          nix run .#gomod2nix
          if [ -n "$(git status --porcelain)" ]; then
            git add gomod2nix.toml
            git commit -m "chore(deps): update gomod2nix"
            git push
          fi
